[project]
name = "smart-sport-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio-ffmpeg>=0.6.0",
    "soccernet>=0.1.62",
    "streamlit>=1.49.1",
    "ultralytics>=8.3.192",
]
